/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package code;

import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author David
 */
public class main extends javax.swing.JFrame {

    BBDD_Manager manager = new BBDD_Manager();
    String tableState = "empty";
    int platforms =0;

    /**
     * Creates new form main
     */
    public main() {
        initComponents();
        components(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addMovie_Frame = new javax.swing.JFrame();
        jLabel1 = new javax.swing.JLabel();
        name_addMovie = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        director_addMovie = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        platforms_addMovie = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        date_addMovie = new javax.swing.JTextField();
        aceptar_addMovie = new javax.swing.JButton();
        addSeries_Frame = new javax.swing.JFrame();
        jLabel5 = new javax.swing.JLabel();
        name_addSeries = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        director_addSeries = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        platforms_addSeries = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        date_addSeries = new javax.swing.JTextField();
        aceptar_addMovie1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        date2_addSeries = new javax.swing.JTextField();
        update_Frame = new javax.swing.JFrame();
        jLabel10 = new javax.swing.JLabel();
        nuevoNombre_update = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        nuevoDirector_update = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        platformComboBox_update = new javax.swing.JComboBox<>();
        accept_update = new javax.swing.JButton();
        addPlatform_Frame = new javax.swing.JFrame();
        jLabel13 = new javax.swing.JLabel();
        name_addPlatform = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        price_addPlatform = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        date_addPlatform = new javax.swing.JTextField();
        accept_addPlatform = new javax.swing.JButton();
        connect_button = new javax.swing.JButton();
        disconnect_button = new javax.swing.JButton();
        restore_button = new javax.swing.JButton();
        allMovies_button = new javax.swing.JButton();
        allSeries_button = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        platform_comboBox = new javax.swing.JComboBox<>();
        seriesFromPlatform_button = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane3 = new javax.swing.JScrollPane();
        mainTable = new javax.swing.JTable();
        seriesandMovies_comboBox = new javax.swing.JComboBox<>();
        deleteSeriesMovies_button = new javax.swing.JButton();
        addSerie_button = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        addMovie_button = new javax.swing.JButton();
        addPlatform_button = new javax.swing.JButton();

        addMovie_Frame.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nombre");
        addMovie_Frame.getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, 20));
        addMovie_Frame.getContentPane().add(name_addMovie, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 90, -1));

        jLabel2.setText("Director");
        addMovie_Frame.getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));
        addMovie_Frame.getContentPane().add(director_addMovie, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 90, -1));

        jLabel3.setText("Plataforma");
        addMovie_Frame.getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        addMovie_Frame.getContentPane().add(platforms_addMovie, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 90, -1));

        jLabel4.setText("Fecha Salida(YYYY-MM-DD)");
        addMovie_Frame.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));
        addMovie_Frame.getContentPane().add(date_addMovie, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 90, -1));

        aceptar_addMovie.setText("Aceptar");
        aceptar_addMovie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptar_addMovieActionPerformed(evt);
            }
        });
        addMovie_Frame.getContentPane().add(aceptar_addMovie, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 260, -1));

        addSeries_Frame.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setText("Nombre");
        addSeries_Frame.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 20));
        addSeries_Frame.getContentPane().add(name_addSeries, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 90, -1));

        jLabel6.setText("Director");
        addSeries_Frame.getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 56, -1, 30));
        addSeries_Frame.getContentPane().add(director_addSeries, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 90, -1));

        jLabel7.setText("Plataforma");
        addSeries_Frame.getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 116, -1, 20));

        addSeries_Frame.getContentPane().add(platforms_addSeries, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 90, -1));

        jLabel8.setText("Fecha Salida(YYYY-MM-DD)");
        addSeries_Frame.getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 156, -1, 20));
        addSeries_Frame.getContentPane().add(date_addSeries, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 90, -1));

        aceptar_addMovie1.setText("Aceptar");
        aceptar_addMovie1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptar_addMovie1ActionPerformed(evt);
            }
        });
        addSeries_Frame.getContentPane().add(aceptar_addMovie1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 300, -1));

        jLabel9.setText("Fecha Finalizacion(YYYY-MM-DD)");
        addSeries_Frame.getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 206, -1, 20));
        addSeries_Frame.getContentPane().add(date2_addSeries, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 90, -1));

        update_Frame.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setText("Nuevo nombre");
        update_Frame.getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 90, -1));
        update_Frame.getContentPane().add(nuevoNombre_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 160, -1));

        jLabel11.setText("Nueva plataforma");
        update_Frame.getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 110, -1));
        update_Frame.getContentPane().add(nuevoDirector_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 160, -1));

        jLabel12.setText("Nuevo director");
        update_Frame.getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 90, -1));

        update_Frame.getContentPane().add(platformComboBox_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 160, -1));

        accept_update.setText("Aceptar");
        accept_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accept_updateActionPerformed(evt);
            }
        });
        update_Frame.getContentPane().add(accept_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 280, -1));

        addPlatform_Frame.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setText("Nombre");
        addPlatform_Frame.getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 80, 40));
        addPlatform_Frame.getContentPane().add(name_addPlatform, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 110, -1));

        jLabel14.setText("Precio");
        addPlatform_Frame.getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 80, 40));
        addPlatform_Frame.getContentPane().add(price_addPlatform, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 110, -1));

        jLabel15.setText("Fecha Salida");
        addPlatform_Frame.getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 80, 40));
        addPlatform_Frame.getContentPane().add(date_addPlatform, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 110, -1));

        accept_addPlatform.setText("Aceptar");
        accept_addPlatform.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accept_addPlatformActionPerformed(evt);
            }
        });
        addPlatform_Frame.getContentPane().add(accept_addPlatform, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 200, -1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1190, 475));
        setPreferredSize(new java.awt.Dimension(1190, 475));
        setSize(new java.awt.Dimension(1190, 475));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        connect_button.setText("Conectar");
        connect_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connect_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(connect_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 20, 90, -1));

        disconnect_button.setText("Desconectar");
        disconnect_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disconnect_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(disconnect_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 20, 110, -1));

        restore_button.setText("Restaurar base de datos");
        restore_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restore_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(restore_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 210, -1));

        allMovies_button.setText("Ver todas las peliculas");
        allMovies_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allMovies_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(allMovies_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 220, -1));

        allSeries_button.setText("Ver todas las series");
        allSeries_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allSeries_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(allSeries_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 220, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 450, 10));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 460, 10));

        getContentPane().add(platform_comboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 160, 30));

        seriesFromPlatform_button.setText("Buscar series y peliculas");
        seriesFromPlatform_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seriesFromPlatform_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(seriesFromPlatform_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 210, -1));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 460, 10));

        mainTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        mainTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mainTableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(mainTable);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, 660, 380));

        getContentPane().add(seriesandMovies_comboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 170, 30));

        deleteSeriesMovies_button.setText("Eliminar series y peliculas");
        deleteSeriesMovies_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteSeriesMovies_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(deleteSeriesMovies_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 200, -1));

        addSerie_button.setText("Añadir serie ");
        addSerie_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSerie_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(addSerie_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, -1, -1));
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 460, 10));

        addMovie_button.setText("Añadir pelicula ");
        addMovie_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMovie_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(addMovie_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, -1, -1));

        addPlatform_button.setText("Añadir plataforma");
        addPlatform_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPlatform_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(addPlatform_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 380, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void connect_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connect_buttonActionPerformed
        if (manager.connection()) {
            manager.checkDatBaseCreated();
            components(true);
        }
    }//GEN-LAST:event_connect_buttonActionPerformed

    private void disconnect_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disconnect_buttonActionPerformed
        manager.disconnection();
        components(false);
    }//GEN-LAST:event_disconnect_buttonActionPerformed

    private void restore_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restore_buttonActionPerformed
        manager.createDataBase();
        updateTable(tableState);
        update();
        System.out.println(tableState);
    }//GEN-LAST:event_restore_buttonActionPerformed

    private void allMovies_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allMovies_buttonActionPerformed
        tableState = "movies";
        DefaultTableModel model = (DefaultTableModel) mainTable.getModel();
        model.getDataVector().removeAllElements();
        model.setColumnCount(4);
        model.setColumnIdentifiers(new Object[]{"Nombre", "Director", "Plataforma", "Fecha Salida"});
        for (int i = 0; i < manager.getFilms().length; i++) {
            model.addRow(new Object[]{manager.getFilms()[i][0], manager.getFilms()[i][1], manager.getFilms()[i][2], manager.getFilms()[i][3]});
        }
    }//GEN-LAST:event_allMovies_buttonActionPerformed

    private void allSeries_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allSeries_buttonActionPerformed
        tableState = "series";
        DefaultTableModel model = (DefaultTableModel) mainTable.getModel();
        model.getDataVector().removeAllElements();
        model.setColumnCount(5);
        model.setColumnIdentifiers(new Object[]{"Nombre", "Director", "Plataforma", "Fecha Salida", "Fecha Finalizacion"});
        for (int i = 0; i < manager.getSeries().length; i++) {
            model.addRow(new Object[]{manager.getSeries()[i][0], manager.getSeries()[i][1], manager.getSeries()[i][2], manager.getSeries()[i][3], manager.getSeries()[i][4]});
        }
    }//GEN-LAST:event_allSeries_buttonActionPerformed

    private void seriesFromPlatform_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seriesFromPlatform_buttonActionPerformed
        tableState = "platforms";
        platforms=platform_comboBox.getSelectedIndex();
        DefaultTableModel model = (DefaultTableModel) mainTable.getModel();
        model.getDataVector().removeAllElements();
        model.setColumnCount(5);
        model.setColumnIdentifiers(new Object[]{"Nombre", "Director", "Plataforma", "Fecha Salida", "Fecha Finalizacion"});
        for (int i = 0; i < manager.getSeriesandMovies(String.valueOf(platform_comboBox.getSelectedIndex())).length; i++) {
            model.addRow(new Object[]{manager.getSeriesandMovies(String.valueOf(platform_comboBox.getSelectedIndex()))[i][0], manager.getSeriesandMovies(String.valueOf(platform_comboBox.getSelectedIndex()))[i][1], manager.getSeriesandMovies(String.valueOf(platform_comboBox.getSelectedIndex()))[i][2], manager.getSeriesandMovies(String.valueOf(platform_comboBox.getSelectedIndex()))[i][3], manager.getSeriesandMovies(String.valueOf(platform_comboBox.getSelectedIndex()))[i][4]});
        }
    }//GEN-LAST:event_seriesFromPlatform_buttonActionPerformed

    private void deleteSeriesMovies_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteSeriesMovies_buttonActionPerformed
        manager.deleteSerieOrMovies(seriesandMovies_comboBox.getSelectedItem().toString());
        updateTable(tableState);
        update();       
    }//GEN-LAST:event_deleteSeriesMovies_buttonActionPerformed

    private void addSerie_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSerie_buttonActionPerformed
        addSeries_Frame.setVisible(true);
        addSeries_Frame.setSize(330, 325);
    }//GEN-LAST:event_addSerie_buttonActionPerformed

    private void addMovie_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMovie_buttonActionPerformed
        addMovie_Frame.setVisible(true);
        addMovie_Frame.setSize(330, 300);
    }//GEN-LAST:event_addMovie_buttonActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        manager.disconnection();
        System.exit(0);
    }//GEN-LAST:event_formWindowClosed

    private void aceptar_addMovieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptar_addMovieActionPerformed
        if (manager.addMovie(name_addMovie.getText(), director_addMovie.getText(), platforms_addMovie.getSelectedIndex(), date_addMovie.getText())) {
            addMovie_Frame.setVisible(false);
            name_addMovie.setText("");
            director_addMovie.setText("");
            platforms_addMovie.setSelectedIndex(0);
            date_addMovie.setText("");
            updateTable(tableState);
            update();
            System.out.println(tableState);
        } else {
            JOptionPane.showMessageDialog(null, "No se pudo añadir la pelicula complete todo los campos o revise la fecha", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_aceptar_addMovieActionPerformed

    private void aceptar_addMovie1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptar_addMovie1ActionPerformed
        if (manager.addSeries(name_addSeries.getText(), director_addSeries.getText(), platforms_addSeries.getSelectedIndex(), date_addSeries.getText(), date2_addSeries.getText())) {
            addSeries_Frame.setVisible(false);
            name_addSeries.setText("");
            director_addSeries.setText("");
            platforms_addSeries.setSelectedIndex(0);
            date_addSeries.setText("");
            date2_addSeries.setText("");
            update();
            updateTable(tableState);
        } else {
            JOptionPane.showMessageDialog(null, "No se pudo añadir la pelicula complete todo los campos o revise la fecha", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_aceptar_addMovie1ActionPerformed

    private void mainTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainTableMouseClicked
        update_Frame.setVisible(true);
        update_Frame.setSize(320, 225);
    }//GEN-LAST:event_mainTableMouseClicked

    private void accept_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accept_updateActionPerformed
        manager.updateSerieOrMovie(mainTable.getValueAt(mainTable.getSelectedRow(), 0).toString(), nuevoNombre_update.getText(), nuevoDirector_update.getText(), platformComboBox_update.getSelectedIndex());
        update_Frame.setVisible(false);
        updateTable(tableState);
        nuevoNombre_update.setText("");
        nuevoDirector_update.setText("");
        platformComboBox_update.setSelectedIndex(0);
    }//GEN-LAST:event_accept_updateActionPerformed

    private void addPlatform_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPlatform_buttonActionPerformed
        addPlatform_Frame.setVisible(true);
        addPlatform_Frame.setSize(278, 244);
    }//GEN-LAST:event_addPlatform_buttonActionPerformed

    private void accept_addPlatformActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accept_addPlatformActionPerformed
        if (manager.addPlatform(name_addPlatform.getText(), Double.parseDouble(price_addPlatform.getText()), date_addPlatform.getText())) {
            name_addPlatform.setText("");
            price_addPlatform.setText("");
            date_addPlatform.setText("");
            updateTable(tableState);
            update();
            addPlatform_Frame.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(null, "No se pudo añadir la pelicula complete todo los campos o revise la fecha", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_accept_addPlatformActionPerformed
    public void components(Boolean state) {
        connect_button.setEnabled(!state);
        disconnect_button.setEnabled(state);
        restore_button.setEnabled(state);
        allMovies_button.setEnabled(state);
        allSeries_button.setEnabled(state);
        platform_comboBox.setEnabled(state);
        seriesFromPlatform_button.setEnabled(state);
        seriesandMovies_comboBox.setEnabled(state);
        deleteSeriesMovies_button.setEnabled(state);
        addMovie_button.setEnabled(state);
        addSerie_button.setEnabled(state);
        addPlatform_button.setEnabled(state);
        if (state) {
            platform_comboBox.addItem("");
            seriesandMovies_comboBox.addItem("");
            platforms_addMovie.addItem("");
            platforms_addSeries.addItem("");
            platformComboBox_update.addItem("");
            for (int i = 0; i < manager.getPlatforms().size(); i++) {
                platform_comboBox.addItem(manager.getPlatforms().get(i));
                platforms_addMovie.addItem(manager.getPlatforms().get(i));
                platforms_addSeries.addItem(manager.getPlatforms().get(i));
                platformComboBox_update.addItem(manager.getPlatforms().get(i));
            }
            for (int i = 0; i < manager.getAllSeriesandMovies().length; i++) {
                seriesandMovies_comboBox.addItem(manager.getAllSeriesandMovies()[i][0]);
            }
        } else {
            for (int i = platform_comboBox.getItemCount() - 1; i >= 0; i--) {
                platform_comboBox.removeItemAt(i);
                platforms_addMovie.removeItemAt(i);
                platforms_addSeries.removeItemAt(i);
                platformComboBox_update.removeItemAt(i);

            }
            for (int i = seriesandMovies_comboBox.getItemCount() - 1; i >= 0; i--) {
                seriesandMovies_comboBox.removeItemAt(i);
            }
        }

    }

    public void update() {
        components(false);
        components(true);
    }

    public void updateTable(String state) {
        if (state.equals("platforms")) {
            System.out.println(state);
            DefaultTableModel model = (DefaultTableModel) mainTable.getModel();
            model.getDataVector().removeAllElements();
            model.setColumnCount(5);
            model.setColumnIdentifiers(new Object[]{"Nombre", "Director", "Plataforma", "Fecha Salida", "Fecha Finalizacion"});
            for (int i = 0; i < manager.getSeriesandMovies(String.valueOf(platform_comboBox.getSelectedIndex())).length; i++) {
                model.addRow(new Object[]{manager.getSeriesandMovies(String.valueOf(platforms))[i][0], manager.getSeriesandMovies(String.valueOf(platform_comboBox.getSelectedIndex()))[i][1], manager.getSeriesandMovies(String.valueOf(platform_comboBox.getSelectedIndex()))[i][2], manager.getSeriesandMovies(String.valueOf(platform_comboBox.getSelectedIndex()))[i][3], manager.getSeriesandMovies(String.valueOf(platform_comboBox.getSelectedIndex()))[i][4]});
            }
        } else if (state.equals("series")) {
            System.out.println(state);
            DefaultTableModel model = (DefaultTableModel) mainTable.getModel();
            model.getDataVector().removeAllElements();
            model.setColumnCount(5);
            model.setColumnIdentifiers(new Object[]{"Nombre", "Director", "Plataforma", "Fecha Salida", "Fecha Finalizacion"});
            for (int i = 0; i < manager.getSeries().length; i++) {
                model.addRow(new Object[]{manager.getSeries()[i][0], manager.getSeries()[i][1], manager.getSeries()[i][2], manager.getSeries()[i][3], manager.getSeries()[i][4]});
            }
        } else if (state.equals("movies")) {
            System.out.println(state);
            DefaultTableModel model = (DefaultTableModel) mainTable.getModel();
            model.getDataVector().removeAllElements();
            model.setColumnCount(4);
            model.setColumnIdentifiers(new Object[]{"Nombre", "Director", "Plataforma", "Fecha Salida"});
            for (int i = 0; i < manager.getFilms().length; i++) {
                model.addRow(new Object[]{manager.getFilms()[i][0], manager.getFilms()[i][1], manager.getFilms()[i][2], manager.getFilms()[i][3]});
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accept_addPlatform;
    private javax.swing.JButton accept_update;
    private javax.swing.JButton aceptar_addMovie;
    private javax.swing.JButton aceptar_addMovie1;
    private javax.swing.JFrame addMovie_Frame;
    private javax.swing.JButton addMovie_button;
    private javax.swing.JFrame addPlatform_Frame;
    private javax.swing.JButton addPlatform_button;
    private javax.swing.JButton addSerie_button;
    private javax.swing.JFrame addSeries_Frame;
    private javax.swing.JButton allMovies_button;
    private javax.swing.JButton allSeries_button;
    private javax.swing.JButton connect_button;
    private javax.swing.JTextField date2_addSeries;
    private javax.swing.JTextField date_addMovie;
    private javax.swing.JTextField date_addPlatform;
    private javax.swing.JTextField date_addSeries;
    private javax.swing.JButton deleteSeriesMovies_button;
    private javax.swing.JTextField director_addMovie;
    private javax.swing.JTextField director_addSeries;
    private javax.swing.JButton disconnect_button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTable mainTable;
    private javax.swing.JTextField name_addMovie;
    private javax.swing.JTextField name_addPlatform;
    private javax.swing.JTextField name_addSeries;
    private javax.swing.JTextField nuevoDirector_update;
    private javax.swing.JTextField nuevoNombre_update;
    private javax.swing.JComboBox<String> platformComboBox_update;
    private javax.swing.JComboBox<String> platform_comboBox;
    private javax.swing.JComboBox<String> platforms_addMovie;
    private javax.swing.JComboBox<String> platforms_addSeries;
    private javax.swing.JTextField price_addPlatform;
    private javax.swing.JButton restore_button;
    private javax.swing.JButton seriesFromPlatform_button;
    private javax.swing.JComboBox<String> seriesandMovies_comboBox;
    private javax.swing.JFrame update_Frame;
    // End of variables declaration//GEN-END:variables
}
